# Generated by Django 4.2.5 on 2023-10-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('uid', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('acc_type', models.CharField(max_length=500)),
            ],
        ),
    ]
